<a href="https://colab.research.google.com/github/sztyberj/Zaawansowane-przetwarzanie-i-integracja-danych---sem.6/blob/main/Zadanie1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [132]:
#import libs
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import preprocessing

In [133]:
#load data
data = pd.read_csv('https://raw.githubusercontent.com/sztyberj/Zaawansowane-przetwarzanie-i-integracja-danych---sem.6/main/Data/DanePogoda.csv',sep=';', encoding_errors="ignore")
data.head(10)

   Stacja        Data   Godzina zjawisko  Zachmurzenia  Cisnienie
0   12570  01.06.2020  00:00:00      Mga             6     1017.7
1   12560  01.06.2020  00:00:00      Mga             6     1018.6
2   12570  01.06.2020  01:00:00      Mga             2     1017.6
3   12560  01.06.2020  01:00:00      Mga             5     1018.6
4   12566  01.06.2020  01:00:00      Mga             4     1018.2
5   12520  01.06.2020  02:00:00      Mga             2     1021.3
6   12560  01.06.2020  02:00:00      Mga             6     1018.5
7   12595  01.06.2020  02:00:00   Deszcz             0     1015.9
8   12566  01.06.2020  02:00:00      Mga             7     1018.0
9   12500  01.06.2020  03:00:00      Mga             0     1023.2

In [134]:
#correct data
data.rename(columns={"zjawisko": "Zjawisko"}, inplace=True)
data.Zjawisko.unique()

array(['Mga', 'Deszcz', 'Burza'], dtype=object)

In [135]:
data.replace(["Mga"], "Mgła", inplace=True)
data.head(10)

   Stacja        Data   Godzina Zjawisko  Zachmurzenia  Cisnienie
0   12570  01.06.2020  00:00:00     Mgła             6     1017.7
1   12560  01.06.2020  00:00:00     Mgła             6     1018.6
2   12570  01.06.2020  01:00:00     Mgła             2     1017.6
3   12560  01.06.2020  01:00:00     Mgła             5     1018.6
4   12566  01.06.2020  01:00:00     Mgła             4     1018.2
5   12520  01.06.2020  02:00:00     Mgła             2     1021.3
6   12560  01.06.2020  02:00:00     Mgła             6     1018.5
7   12595  01.06.2020  02:00:00   Deszcz             0     1015.9
8   12566  01.06.2020  02:00:00     Mgła             7     1018.0
9   12500  01.06.2020  03:00:00     Mgła             0     1023.2

In [136]:
#Zadanie 1.1
for i in data.Godzina:
  if '06:00:00' <= i <= '17:00:00':
    data.Godzina.replace(i, 'rano', inplace=True)
  if '18:00:00' <= i <= '20:00:00':
    data.Godzina.replace(i, 'wieczór', inplace=True)
  if  i <= '05:00:00':
    data.Godzina.replace(i, 'noc', inplace=True)
  if i == '21:00:00' or i == '22:00:00' or i == '23:00:00':
    data.Godzina.replace(i, 'noc', inplace=True)
  
data.Godzina.head(20)

0         noc
1         noc
2         noc
3         noc
4         noc
5         noc
6         noc
7         noc
8         noc
9         noc
10        noc
11        noc
12        noc
13        noc
14        noc
15        noc
16        noc
17       rano
18    wieczór
19        noc
Name: Godzina, dtype: object

In [137]:
#Zadanie 1.2
for i in data.Zachmurzenia:
  if i == 0:
    data.Zachmurzenia.replace(i, 'Brak', inplace=True)
  if 1 <= i <= 3:
    data.Zachmurzenia.replace(i, 'małe', inplace=True)
  if 4 <= i <= 5:
    data.Zachmurzenia.replace(i, 'umiarkowane', inplace=True)
  if 6 <= i <= 7:
    data.Zachmurzenia.replace(i, 'duże', inplace=True)
  if i == 8:
    data.Zachmurzenia.replace(i, 'pełne', inplace=True)

data.Zachmurzenia.head(20)

0            duże
1            duże
2            małe
3     umiarkowane
4     umiarkowane
5            małe
6            duże
7            Brak
8            duże
9            Brak
10           małe
11           duże
12           małe
13           Brak
14           małe
15           małe
16           małe
17           małe
18           Brak
19           małe
Name: Zachmurzenia, dtype: object

In [138]:
#Zadanie 1.3
max = data.Cisnienie.max()
min = data.Cisnienie.min()
arr = []

for i in data.Cisnienie:
  norm_i = (i - min) / (max - min)
  arr.append(norm_i)

normalized_ser = pd.Series(arr)
data.Cisnienie.replace([data.Cisnienie], [normalized_ser], inplace=True)

data.Cisnienie.head(20)

0     0.721485
1     0.745358
2     0.718833
3     0.745358
4     0.734748
5     0.816976
6     0.742706
7     0.673740
8     0.729443
9     0.867374
10    0.819629
11    0.734748
12    0.724138
13    0.872679
14    0.827586
15    0.734748
16    0.824934
17    0.758621
18    0.729443
19    0.809019
Name: Cisnienie, dtype: float64

In [139]:
#Zadanie 4
data = pd.get_dummies(data, columns=['Godzina'])
data.head(20)

,Stacja,Data,Zjawisko,Zachmurzenia,Cisnienie,Godzina_noc,Godzina_rano,Godzina_wieczór
0,12570,01.06.2020,Mgła,duże,0.721485,1,0,0
1,12560,01.06.2020,Mgła,duże,0.745358,1,0,0
2,12570,01.06.2020,Mgła,małe,0.718833,1,0,0
3,12560,01.06.2020,Mgła,umiarkowane,0.745358,1,0,0
4,12566,01.06.2020,Mgła,umiarkowane,0.734748,1,0,0
5,12520,01.06.2020,Mgła,małe,0.816976,1,0,0
6,12560,01.06.2020,Mgła,duże,0.742706,1,0,0
7,12595,01.06.2020,Deszcz,Brak,0.673740,1,0,0
8,12566,01.06.2020,Mgła,duże,0.729443,1,0,0
9,12500,01.06.2020,Mgła,Brak,0.867374,1,0,0
10,12520,01.06.2020,Mgła,małe,0.819629,1,0,0
11,12566,01.06.2020,Mgła,duże,0.734748,1,0,0
12,12570,01.06.2020,Mgła,małe,0.724138,1,0,0
13,12500,01.06.2020,Mgła,Brak,0.872679,1,0,0
14,12520,01.06.2020,Mgła,małe,0.827586,1,0,0
15,12566,01.06.2020,Mgła,małe,0.734748,1,0,0
16,12520,01.06.2020,Mgła,małe,0.824934,1,0,0
17,12520,01.06.2020,Deszcz,małe,0.758621,0,1,0
18,12285,01.06.2020,Deszcz,Brak,0.729443,0,0,1
19,12500,02.06.2020,Mgła,małe,0.809019,1,0,0

In [140]:
#Zadanie 5
data = pd.get_dummies(data, columns=['Zjawisko'])
data.head(20)

,Stacja,Data,Zachmurzenia,Cisnienie,Godzina_noc,Godzina_rano,Godzina_wieczór,Zjawisko_Burza,Zjawisko_Deszcz,Zjawisko_Mgła
0,12570,01.06.2020,duże,0.721485,1,0,0,0,0,1
1,12560,01.06.2020,duże,0.745358,1,0,0,0,0,1
2,12570,01.06.2020,małe,0.718833,1,0,0,0,0,1
3,12560,01.06.2020,umiarkowane,0.745358,1,0,0,0,0,1
4,12566,01.06.2020,umiarkowane,0.734748,1,0,0,0,0,1
5,12520,01.06.2020,małe,0.816976,1,0,0,0,0,1
6,12560,01.06.2020,duże,0.742706,1,0,0,0,0,1
7,12595,01.06.2020,Brak,0.673740,1,0,0,0,1,0
8,12566,01.06.2020,duże,0.729443,1,0,0,0,0,1
9,12500,01.06.2020,Brak,0.867374,1,0,0,0,0,1
10,12520,01.06.2020,małe,0.819629,1,0,0,0,0,1
11,12566,01.06.2020,duże,0.734748,1,0,0,0,0,1
12,12570,01.06.2020,małe,0.724138,1,0,0,0,0,1
13,12500,01.06.2020,Brak,0.872679,1,0,0,0,0,1
14,12520,01.06.2020,małe,0.827586,1,0,0,0,0,1
15,12566,01.06.2020,małe,0.734748,1,0,0,0,0,1
16,12520,01.06.2020,małe,0.824934,1,0,0,0,0,1
17,12520,01.06.2020,małe,0.758621,0,1,0,0,1,0
18,12285,01.06.2020,Brak,0.729443,0,0,1,0,1,0
19,12500,02.06.2020,małe,0.809019,1,0,0,0,0,1

In [141]:
data = pd.get_dummies(data, columns=['Zachmurzenia'])
data.head(20)

,Stacja,Data,Cisnienie,Godzina_noc,Godzina_rano,Godzina_wieczór,Zjawisko_Burza,Zjawisko_Deszcz,Zjawisko_Mgła,Zachmurzenia_Brak,Zachmurzenia_duże,Zachmurzenia_małe,Zachmurzenia_pełne,Zachmurzenia_umiarkowane
0,12570,01.06.2020,0.721485,1,0,0,0,0,1,0,1,0,0,0
1,12560,01.06.2020,0.745358,1,0,0,0,0,1,0,1,0,0,0
2,12570,01.06.2020,0.718833,1,0,0,0,0,1,0,0,1,0,0
3,12560,01.06.2020,0.745358,1,0,0,0,0,1,0,0,0,0,1
4,12566,01.06.2020,0.734748,1,0,0,0,0,1,0,0,0,0,1
5,12520,01.06.2020,0.816976,1,0,0,0,0,1,0,0,1,0,0
6,12560,01.06.2020,0.742706,1,0,0,0,0,1,0,1,0,0,0
7,12595,01.06.2020,0.673740,1,0,0,0,1,0,1,0,0,0,0
8,12566,01.06.2020,0.729443,1,0,0,0,0,1,0,1,0,0,0
9,12500,01.06.2020,0.867374,1,0,0,0,0,1,1,0,0,0,0
10,12520,01.06.2020,0.819629,1,0,0,0,0,1,0,0,1,0,0
11,12566,01.06.2020,0.734748,1,0,0,0,0,1,0,1,0,0,0
12,12570,01.06.2020,0.724138,1,0,0,0,0,1,0,0,1,0,0
13,12500,01.06.2020,0.872679,1,0,0,0,0,1,1,0,0,0,0
14,12520,01.06.2020,0.827586,1,0,0,0,0,1,0,0,1,0,0
15,12566,01.06.2020,0.734748,1,0,0,0,0,1,0,0,1,0,0
16,12520,01.06.2020,0.824934,1,0,0,0,0,1,0,0,1,0,0
17,12520,01.06.2020,0.758621,0,1,0,0,1,0,0,0,1,0,0
18,12285,01.06.2020,0.729443,0,0,1,0,1,0,1,0,0,0,0
19,12500,02.06.2020,0.809019,1,0,0,0,0,1,0,0,1,0,0